#include "instructions.h"

instruction_t instructions[INSTRUCTION_COUNT] = {
    // NOP
    [0x00] = {ADDRESSING_IMPLICIT, ADDRESSING_IMPLICIT, nop, "NOP"},
    // MOV A, #value
    [0x74] = {ADDRESSING_IMPLICIT, ADDRESSING_IMMEDIATE, mov, "MOV A, #0x%02x"},
    // MOV (adr), #value
    [0x75] = {ADDRESSING_DIRECT, ADDRESSING_IMMEDIATE, mov, "MOV (0x?\?), #0x%02x"},
    // MOV (Ri), #value
    [0x76] = {ADDRESSING_REGISTER_INDIRECT, ADDRESSING_IMMEDIATE, mov, "MOV (R0), #0x%02x"},
    [0x77] = {ADDRESSING_REGISTER_INDIRECT, ADDRESSING_IMMEDIATE, mov, "MOV (R1), #0x%02x"},
    // MOV Rn, #value
    [0x78] = {ADDRESSING_REGISTER, ADDRESSING_IMMEDIATE, mov, "MOV R0, #0x%02x"},
    [0x79] = {ADDRESSING_REGISTER, ADDRESSING_IMMEDIATE, mov, "MOV R1, #0x%02x"},
    [0x7A] = {ADDRESSING_REGISTER, ADDRESSING_IMMEDIATE, mov, "MOV R2, #0x%02x"},
    [0x7B] = {ADDRESSING_REGISTER, ADDRESSING_IMMEDIATE, mov, "MOV R3, #0x%02x"},
    [0x7C] = {ADDRESSING_REGISTER, ADDRESSING_IMMEDIATE, mov, "MOV R4, #0x%02x"},
    [0x7D] = {ADDRESSING_REGISTER, ADDRESSING_IMMEDIATE, mov, "MOV R5, #0x%02x"},
    [0x7E] = {ADDRESSING_REGISTER, ADDRESSING_IMMEDIATE, mov, "MOV R6, #0x%02x"},
    [0x7F] = {ADDRESSING_REGISTER, ADDRESSING_IMMEDIATE, mov, "MOV R7, #0x%02x"},
    // MOV (adr), (adr1)
    [0x85] = {ADDRESSING_DIRECT, ADDRESSING_DIRECT, mov, "MOV (0x?\?), (0x%02x)"},
    // MOV (adr), (Ri)
    [0x86] = {ADDRESSING_DIRECT, ADDRESSING_REGISTER_INDIRECT, mov, "MOV (0x?\?), (R0)"},
    [0x87] = {ADDRESSING_DIRECT, ADDRESSING_REGISTER_INDIRECT, mov, "MOV (0x?\?), (R1)"},
    // MOV (adr), Rn
    [0x88] = {ADDRESSING_DIRECT, ADDRESSING_REGISTER, mov, "MOV (0x?\?), R0"},
    [0x89] = {ADDRESSING_DIRECT, ADDRESSING_REGISTER, mov, "MOV (0x?\?), R1"},
    [0x8A] = {ADDRESSING_DIRECT, ADDRESSING_REGISTER, mov, "MOV (0x?\?), R2"},
    [0x8B] = {ADDRESSING_DIRECT, ADDRESSING_REGISTER, mov, "MOV (0x?\?), R3"},
    [0x8C] = {ADDRESSING_DIRECT, ADDRESSING_REGISTER, mov, "MOV (0x?\?), R4"},
    [0x8D] = {ADDRESSING_DIRECT, ADDRESSING_REGISTER, mov, "MOV (0x?\?), R5"},
    [0x8E] = {ADDRESSING_DIRECT, ADDRESSING_REGISTER, mov, "MOV (0x?\?), R6"},
    [0x8F] = {ADDRESSING_DIRECT, ADDRESSING_REGISTER, mov, "MOV (0x?\?), R7"},
    // MOV (Ri), (adr)
    [0xA6] = {ADDRESSING_REGISTER_INDIRECT, ADDRESSING_DIRECT, mov, "MOV (R0), (0x%02x)"},
    [0xA7] = {ADDRESSING_REGISTER_INDIRECT, ADDRESSING_DIRECT, mov, "MOV (R1), (0x%02x)"},
    // MOV Rn, (adr)
    [0xA8] = {ADDRESSING_REGISTER, ADDRESSING_DIRECT, mov, "MOV R0, (0x%02x)"},
    [0xA9] = {ADDRESSING_REGISTER, ADDRESSING_DIRECT, mov, "MOV R1, (0x%02x)"},
    [0xAA] = {ADDRESSING_REGISTER, ADDRESSING_DIRECT, mov, "MOV R2, (0x%02x)"},
    [0xAB] = {ADDRESSING_REGISTER, ADDRESSING_DIRECT, mov, "MOV R3, (0x%02x)"},
    [0xAC] = {ADDRESSING_REGISTER, ADDRESSING_DIRECT, mov, "MOV R4, (0x%02x)"},
    [0xAD] = {ADDRESSING_REGISTER, ADDRESSING_DIRECT, mov, "MOV R5, (0x%02x)"},
    [0xAE] = {ADDRESSING_REGISTER, ADDRESSING_DIRECT, mov, "MOV R6, (0x%02x)"},
    [0xAF] = {ADDRESSING_REGISTER, ADDRESSING_DIRECT, mov, "MOV R7, (0x%02x)"},
    // MOV A, (adr)
    [0xE5] = {ADDRESSING_IMPLICIT, ADDRESSING_DIRECT, mov, "MOV A, (0x%02x)"},
    // MOV A, (Ri)
    [0xE6] = {ADDRESSING_IMPLICIT, ADDRESSING_REGISTER_INDIRECT, mov, "MOV A, (R0)"},
    [0xE7] = {ADDRESSING_IMPLICIT, ADDRESSING_REGISTER_INDIRECT, mov, "MOV A, (R1)"},
    // MOV A, Rn
    [0xE8] = {ADDRESSING_IMPLICIT, ADDRESSING_REGISTER, mov, "MOV A, R0"},
    [0xE9] = {ADDRESSING_IMPLICIT, ADDRESSING_REGISTER, mov, "MOV A, R1"},
    [0xEA] = {ADDRESSING_IMPLICIT, ADDRESSING_REGISTER, mov, "MOV A, R2"},
    [0xEB] = {ADDRESSING_IMPLICIT, ADDRESSING_REGISTER, mov, "MOV A, R3"},
    [0xEC] = {ADDRESSING_IMPLICIT, ADDRESSING_REGISTER, mov, "MOV A, R4"},
    [0xED] = {ADDRESSING_IMPLICIT, ADDRESSING_REGISTER, mov, "MOV A, R5"},
    [0xEE] = {ADDRESSING_IMPLICIT, ADDRESSING_REGISTER, mov, "MOV A, R6"},
    [0xEF] = {ADDRESSING_IMPLICIT, ADDRESSING_REGISTER, mov, "MOV A, R7"},
    // MOV (adr), A
    [0xF5] = {ADDRESSING_DIRECT, ADDRESSING_IMPLICIT, mov, "MOV (0x?\?), A"},
    // MOV (Ri), A
    [0xF6] = {ADDRESSING_REGISTER_INDIRECT, ADDRESSING_IMPLICIT, mov, "MOV (R0), A"},
    [0xF7] = {ADDRESSING_REGISTER_INDIRECT, ADDRESSING_IMPLICIT, mov, "MOV (R1), A"},
    // MOV Rn, A
    [0xF8] = {ADDRESSING_REGISTER, ADDRESSING_IMPLICIT, mov, "MOV R0, A"},
    [0xF9] = {ADDRESSING_REGISTER, ADDRESSING_IMPLICIT, mov, "MOV R1, A"},
    [0xFA] = {ADDRESSING_REGISTER, ADDRESSING_IMPLICIT, mov, "MOV R2, A"},
    [0xFB] = {ADDRESSING_REGISTER, ADDRESSING_IMPLICIT, mov, "MOV R3, A"},
    [0xFC] = {ADDRESSING_REGISTER, ADDRESSING_IMPLICIT, mov, "MOV R4, A"},
    [0xFD] = {ADDRESSING_REGISTER, ADDRESSING_IMPLICIT, mov, "MOV R5, A"},
    [0xFE] = {ADDRESSING_REGISTER, ADDRESSING_IMPLICIT, mov, "MOV R6, A"},
    [0xFF] = {ADDRESSING_REGISTER, ADDRESSING_IMPLICIT, mov, "MOV R7, A"}
};  